{
 "title": "Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fire",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fire_probability" }
   ]
  },
  {
   "title": "Prediction Distributions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prediction_output_distribution_sum[30s]))/sum(increase(prediction_output_distribution_count[30s]))",
     "legendFormat": "Avg. Prediction Distribution Increase"
    },
    {
     "expr": "sum(increase(prediction_score_distribution_sum[30s])) / sum(increase(prediction_score_distribution_count[30s]))",
     "legendFormat": "Avg. Anomaly Score Distribution Increase"
    }
   ]
  },
  {
   "title": "Hydrogen concentration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "hydrogen_concentration" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "temperature_celsius" }
   ]
  },
  {
   "title": "Humidity Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "humidity_percentage" }
   ]
  },
  {
   "title": "Fire Probability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "fire_probability" }
   ]
  },
  {
   "title": "Latency Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prediction_latency_distribution_sum[30s]))/sum(increase(prediction_latency_distribution_count[30s]))",
     "legendFormat": "Prediction Latency"
    }
   ]
  },
  {
   "title": "Prediction and Model Info Request Counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(num_prediction_requests_total[5m])",
     "legendFormat": "Prediction Request Call Rate in Last 5 Minutes"
    },
    {
     "expr": "rate(num_model_info_requests_total[5m])",
     "legendFormat": "Model Info Request Call Rate in Last 5 Minutes"
    }
   ]
  }
 ]
}